<?php
/**
 * Plugin adapter for YayExtra Lite - WooCommerce Extra Product Option.
 * Generated by yaycommerce-init. Edit values as needed.
 */

defined( 'ABSPATH' ) || exit;

class YayextraPluginAdapter implements \YayExtraScoped\YayCommerce\AdminShell\Contracts\PluginMenuAdapter {
    public function get_menu_title(): string         { return 'YayExtra'; }
    public function get_page_title(): string         { return 'YayExtra Lite - WooCommerce Extra Product Option'; }
    public function get_menu_slug(): string          { return 'yayextra'; }
    public function get_settings_page_callback(): ?callable { return function(){
		?> 
		<script>
			document.querySelector("#wpbody-content").innerHTML = "";
		</script>
		<div id="yayextra-section"></div>
		<?php
	}; } // Set your render callback here
    public function get_settings_page_position(): ?int { return 201; }
    public function get_capability(): string         { return 'manage_options'; }
    public function get_plugin_basename(): string    { return YAYE_BASENAME; }
    public function get_settings_label(): string     { return 'Settings'; }
    public function get_docs_url(): string           { return 'https://docs.yaycommerce.com/yayextra/'; }
    public function get_pro_url(): string            { return 'https://yaycommerce.com/yayextra-woocommerce-extra-product-options/'; }

}
